-- MySQL Script generated by MySQL Workbench
-- 07/17/16 20:04:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema flashbd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema flashbd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flashbd` DEFAULT CHARACTER SET utf8 ;
USE `flashbd` ;

-- -----------------------------------------------------
-- Table `flashbd`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flashbd`.`usuarios` (
  `username` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` INT NULL,
  `email` VARCHAR(45) NULL,
  `empresa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flashbd`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flashbd`.`clientes` (
  `idclientes` INT NOT NULL AUTO_INCREMENT,
  `nombre y apellido` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `mail` VARCHAR(80) NULL,
  `usuarios_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idclientes`, `usuarios_username`),
  INDEX `fk_clientes_usuarios1_idx` (`usuarios_username` ASC),
  CONSTRAINT `fk_clientes_usuarios1`
    FOREIGN KEY (`usuarios_username`)
    REFERENCES `flashbd`.`usuarios` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flashbd`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flashbd`.`categorias` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `imagen` VARCHAR(100) NULL,
  `usuarios_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`, `usuarios_username`),
  INDEX `fk_categorias_usuarios1_idx` (`usuarios_username` ASC),
  CONSTRAINT `fk_categorias_usuarios1`
    FOREIGN KEY (`usuarios_username`)
    REFERENCES `flashbd`.`usuarios` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flashbd`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flashbd`.`productos` (
  `idproductos` INT NOT NULL AUTO_INCREMENT,
  `idCategoria` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `stock` INT NULL,
  `imagen` VARCHAR(100) NULL,
  `costo` FLOAT NULL,
  `precio` FLOAT NOT NULL,
  `usuarios_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproductos`, `idCategoria`, `usuarios_username`),
  INDEX `fk_productos_categorias1_idx` (`idCategoria` ASC),
  INDEX `fk_productos_usuarios1_idx` (`usuarios_username` ASC),
  CONSTRAINT `fk_productos_categorias1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `flashbd`.`categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_usuarios1`
    FOREIGN KEY (`usuarios_username`)
    REFERENCES `flashbd`.`usuarios` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flashbd`.`cadetes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flashbd`.`cadetes` (
  `idCadete` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(25) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NULL,
  `usuarios_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCadete`, `usuarios_username`),
  INDEX `fk_cadetes_usuarios1_idx` (`usuarios_username` ASC),
  CONSTRAINT `fk_cadetes_usuarios1`
    FOREIGN KEY (`usuarios_username`)
    REFERENCES `flashbd`.`usuarios` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flashbd`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flashbd`.`pedidos` (
  `nroPedido` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `idCadete` INT NOT NULL,
  `fecha` DATE NULL,
  `usuarios_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nroPedido`, `idCliente`, `idCadete`, `usuarios_username`),
  INDEX `fk_pedidos_clientes1_idx` (`idCliente` ASC),
  INDEX `fk_pedidos_cadetes1_idx` (`idCadete` ASC),
  INDEX `fk_pedidos_usuarios1_idx` (`usuarios_username` ASC),
  CONSTRAINT `fk_pedidos_clientes1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `flashbd`.`clientes` (`idclientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_cadetes1`
    FOREIGN KEY (`idCadete`)
    REFERENCES `flashbd`.`cadetes` (`idCadete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_usuarios1`
    FOREIGN KEY (`usuarios_username`)
    REFERENCES `flashbd`.`usuarios` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flashbd`.`pedidos_has_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flashbd`.`pedidos_has_productos` (
  `nroPedido` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `usuarios_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nroPedido`, `idProducto`, `usuarios_username`),
  INDEX `fk_pedidos_has_productos_productos1_idx` (`idProducto` ASC),
  INDEX `fk_pedidos_has_productos_pedidos1_idx` (`nroPedido` ASC),
  INDEX `fk_pedidos_has_productos_usuarios1_idx` (`usuarios_username` ASC),
  CONSTRAINT `fk_pedidos_has_productos_pedidos1`
    FOREIGN KEY (`nroPedido`)
    REFERENCES `flashbd`.`pedidos` (`nroPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_has_productos_productos1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `flashbd`.`productos` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_has_productos_usuarios1`
    FOREIGN KEY (`usuarios_username`)
    REFERENCES `flashbd`.`usuarios` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
